version: '3.3'

services:
  db:
    container_name: misp_db
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  web:
    build: web
    container_name: misp_web
    image: misp:latest
    restart: unless-stopped
    depends_on:
      - "db"
    volumes:
      - ${DATA_DIR}/web:/var/www/MISP
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PGP_EMAIL=${PGP_EMAIL}
      - PGP_PASSPHRASE=${PGP_PASSPHRASE}
      - MISP_ORG=${MISP_ORG}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}

  proxy:
    build:
      context: proxy
      args:
       - MISP_FQDN=${MISP_FQDN}
    container_name: proxy
    restart: unless-stopped
    image: misp-proxy:latest
    depends_on:
      - "web"
    ports:
      - 80:80
      - 443:443